WARNING    - 2024-04-02 14:43:19,304 - client          : PyNaCl is not installed, voice will NOT be supported
INFO       - 2024-04-02 14:43:19,320 - client          : logging in using static token
INFO       - 2024-04-02 14:43:26,516 - gateway         : Shard ID None has connected to Gateway (Session ID: fc9eb7e48a0975745a1d32c4736f5d2e).
ERROR      - 2024-04-02 14:43:28,403 - bot             : Ignoring exception in command salmon
Traceback (most recent call last):
  File "C:\Users\E\Documents\Personal projects\discordbot\.venv\lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\E\Documents\Personal projects\discordbot\splatink\rotationcmds.py", line 61, in salmon
    await ctx.send(rotation.get_salmon())
  File "C:\Users\E\Documents\Personal projects\discordbot\splatink\stageinfo.py", line 150, in get_salmon
    salm = cls.getdata()[
KeyError: 'data'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\E\Documents\Personal projects\discordbot\.venv\lib\site-packages\discord\ext\commands\bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\E\Documents\Personal projects\discordbot\.venv\lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\E\Documents\Personal projects\discordbot\.venv\lib\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'data'
